### ISSUE TITLE
Transaction pending; not broadcast

### ISSUE THREAD

**Issue by Ogletree** [Cryptonomic/Deployments#13]
Transaction stays on pending forever. Clicking the link shows not the transaction hash, but this weird mesg;
path [{kind:branch,id:proto.002-PsYLVpVv.contract.counter_in_the_past,contract:tz1myaddresshere,expected:1483,found:1482}] not found

![image](https://user-images.githubusercontent.com/799559/47803417-0cd3b000-dcf8-11e8-9c04-c31dea6f8770.png)

**Comment by Ogletree** [comment]
Windows v0.3.0b

**Comment by umurb** [comment]
Hi @Ogletree sorry for the delayed response.

Are you still experiencing such problems with Galleon? Our most recent release, v0.6.1b should be working fine with protocol 003.

Please let me know
