### ISSUE TITLE
Galleon: German Translation: "Befor wir anfangen lesen Sie..."

### ISSUE THREAD

**Issue by djangobits** [Cryptonomic/Deployments#17]
IS: 
`Befor wir anfangen lesen Sie bitte und bestätigen Sie unsere Nutzungsbedingungen und Datenschutz-Bestimmungen`

SHOULD:
`Bevor wir anfangen, lesen und bestätigen Sie bitte unsere Nutzungsbedingungen und Datenschutzbestimmungen`

**Comment by umurb** [comment]
Will be fixed in our upcoming release.

Thank you!
