### ISSUE TITLE
Add 2FA please

### ISSUE THREAD

**Issue by raspatan** [Cryptonomic/Deployments#18]
Hi there, great software!

A humble request. Is it possible to add two-factor authentication to Galleon? E.g. via a smartphone app? This would greatly enhance security of the wallet, imo.

Keep up the good work!

Thanks.

**Comment by anonymoussprocket** [comment]
Hi raspatan. Thank you for the suggestion and the kind words. I opened a ticket in the Tezori repo as this functionality would need to go there.

https://github.com/Cryptonomic/Tezori/issues/597
