### ISSUE TITLE
Alphanet support

### ISSUE THREAD

**Issue by ConsentDevelopment** [Cryptonomic/Deployments#21]
The Galleon wallet currently does not support working on the Alphanet.  I understand this is not a priority but it would be very useful to both users and developers to try out operations with no harm done as it is only the Alphanet.

I tried adding a custom Alphanet node to the settings and the app gave the following error message - **'It seems the Tezos node you are using is either stuck or on the wrong network. Please delay further actions.'**

Which makes sense as the wallet is expecting to work on the Mainnet network,

**Comment by umurb** [comment]
Hi,

Galleon wallet does support Alphanet. Switching your Tezos Node is not enough though, you should also switch your Conseil node. To access our instance of Conseil node running on Alphanet, please join our developers room in Riot - https://riot.im/app/#/room/#cryptonomic-developers:cryptonomic.tech
