### ISSUE TITLE
Terms & Privacy Policy missing

### ISSUE THREAD

**Issue by awasunyin** [Cryptonomic/Deployments#3]
Hi! Tried the MacOS version of Galleon: 
The Terms and Privacy Policy are missing.
 
<img width="1031" alt="screen shot 2018-07-25 at 09 26 17" src="https://user-images.githubusercontent.com/11296013/43258846-8a866c06-90d4-11e8-9d8a-b09ee3d6ada0.png">
<img width="1030" alt="screen shot 2018-07-25 at 09 26 27" src="https://user-images.githubusercontent.com/11296013/43258850-8bff14d4-90d4-11e8-8425-8590651a787f.png">

**Comment by umurb** [comment]
Again, sorry for the radio silence.

Please let me know if you can reproduce this error with the most recent release of Galleon, v0.6.1b
