### ISSUE TITLE
About Customised Full Nodes

### ISSUE THREAD

**Issue by awasunyin** [Cryptonomic/Deployments#4]
It's great that you're supporting custom full nodes! 

I have two questions on this feature:

1) What's the difference between adding a custom full node under "Conseil Nodes" and "Tezos Nodes"?

2) Could we have the feature of "saving node preferences?", so next time I open Galleon and this wallet, I don't have to reset the customised full node. 

<img width="1217" alt="screen shot 2018-07-25 at 09 33 44" src="https://user-images.githubusercontent.com/11296013/43260563-2cb083c2-90da-11e8-8022-e9960aeba9cc.png">

Cheers!

**Comment by umurb** [comment]
Hi @awasunyin Sorry for the radio silence on this one. I've responded you question in #14 

Conseil is a query service we, Cryptonomic, developed. It can be found here: https://github.com/Cryptonomic/Conseil

The wallet settings should be persistent within our newest release v0.6.1b
