### ISSUE TITLE
'Not enough fee' alert message - improvement

### ISSUE THREAD

**Issue by Corfucinas** [Cryptonomic/Deployments#43]
Hi, I noticed that when sending from a KT1 address (since with the new protocols the fee is now paid from the tz1), in case the balance is too low to cover the transaction, there's no prompt alert. Currently, it behaves as it tries send it normally, however, the transaction will fail.

It would be an improvement having an alert of either `balance/fee too low/insufficient`  when this situation happens.

**Comment by shaun19826** [comment]
Hello, are you still having this issue or has the issue been resolved ?

**Comment by Corfucinas** [comment]
Hi, I'll reverify.
This originated because I have an old KT1 address as a delegator and when I tried to send payments it deducts the fee from the tz1 from where it originated. Basically, I found out that if there was now fee I wouldn't get neither a confirmation nor transaction failed message (I also have the latest wallet build)

**Comment by shaun19826** [comment]
So you're still having this issue ?
I was going to help with a solution that's why I asked.

**Comment by Corfucinas** [comment]
Yes, last transaction was 2 cycles ago, I was going to retry soon.

What is your suggestion?

**Comment by shaun19826** [comment]
My suggestion is that you try on the galleon web wallet.
To do so, restore your wallet via the galleon web wallet on www.galleon.network ;after you’ve successfully restored your wallet, proceed to your delegations and try to change your baker.
On the galleon web wallet, you’re allowed features which shows the list of all bakers with high payout options and low fees. You’re allowed to select from whichever you want.

You can do that and get back to me on whatever the update is.
Cheers mate

**Comment by shaun19826** [comment]
My suggestion is that you try on the galleon web wallet.
To do so, restore your wallet via the galleon web wallet on www.galleon.network ;after you’ve successfully restored your wallet, proceed to your delegations and try to change your baker.
On the galleon web wallet, you’re allowed features which shows the list of all bakers with high payout options and low fees. You’re allowed to select from whichever you want.

You can do that and get back to me on whatever the update is.
Cheers mate

**Comment by shaun19826** [comment]
@Corfucinas Have you been to fix it with the steps I left out ?

**Comment by Corfucinas** [comment]
Hi @shaun19826 

Yeah, that works fine. I actually just moved the old wallet to a new tz1, I think you can close this. Let you know if somethings comes up.

**Comment by shaun19826** [comment]
Okay that’s good.
You can try accessing the galleon web wallet via www.galleon.network to get
a list of bakers with high payout options and low fees.
You’re welcome.
Cheers

**Comment by shaun19826** [comment]
@Corfucinas Do let me know if you've accessed the galleon web wallet via www.galleon.network to get
a list of bakers with high payout options and low fees.
Cheers

**Comment by Corfucinas** [comment]
@shaun19826  yes, all good
