### ISSUE TITLE
Galleon won't start

### ISSUE THREAD

**Issue by neg3ntropy** [Cryptonomic/Deployments#48]
```
$ galleon
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "galleon"
Segmentation fault (core dumped)
```

Fedora 33, fresh install via snap. cgroups v1 or v2 does not change. The snap hello world works.
I don't know how to debug a snap package further.

**Comment by shaun-19826** [comment]
Hello, has your issue been resolved or you're still having this issue ?
