### ISSUE TITLE
Explain what betanet and zeronet are on Downloads wiki page

### ISSUE THREAD

**Issue by nyeates** [Cryptonomic/Deployments#5]
I am new and had no idea which Galleon to download from the wiki page. I had to research it for 20 mins. Also, the wiki page is missing contextual info. Assume that a brand-new novice is coming straight to this page from a google search, knowing very little. Make this community user-friendly to new users!

On https://github.com/Cryptonomic/Deployments/wiki/Galleon

Solution:
Next to betanet, write "(pre-mainnet; will be used as real network going forward)"
Next to zeronet, write "(test network for software developers; cutting edge)"

**Comment by umurb** [comment]
Great advice. Added descriptions to betanet and zeronet in releases & downloads page;

https://github.com/Cryptonomic/Deployments/wiki/Galleon:-Releases
