### ISSUE TITLE
It seems the conseil server is not synced with the tezos network

### ISSUE THREAD

**Issue by cfw34683** [Cryptonomic/Deployments#51]
The windows store app is telling us this and we are getting reports of it on reddit too at https://www.reddit.com/r/tezos/comments/jy6hih/it_seems_the_conseil_server_is_not_synced_with/  
please help us

**Comment by gologo13** [comment]
I had the same issue..

**Comment by cfw34683** [comment]
This issue has been resolved by the team. There was nothing to do on my end. This was a server issue on their end. Please close
