### ISSUE TITLE
Error withdrawing funds from delegation contract to manager address

### ISSUE THREAD

**Issue by planetgargalon** [Cryptonomic/Deployments#57]
I'm getting the following comment - Cannot read property 'signOperation' of null. I've tried with different amounts and gas fees, nothing seems to work. The manager wallet has enough Tezos to fund the transaction - tz1cvj2NBZAnHcQUVxaa2F7DzFa6qDJoVT86

**Comment by shaun-19826** [comment]
I had the same issue too earlier but I had mine resolved already. Contact
tezos Foundations on telegram www.t.me/thetezosfoundations

They’ll be happy to get sorted out for you.
Cheers.

**Comment by shaun-19826** [comment]
@planetgargalon Have you gotten your issue resolved ?

I didn't get a feedback from you.

**Comment by anonymoussprocket** [comment]
Please restart Galleon and try again. This should be a transient error.
