### ISSUE TITLE
i got empty page when i open wallet

### ISSUE THREAD

**Issue by fhalaseeri** [Cryptonomic/Deployments#8]
Hello there,,

i have problem with open an existing wallet when i upload the file and put my password i just got an empty page with nothing i can see like in pic below can someone help me to fix this issue?

Thanks
![galleon](https://user-images.githubusercontent.com/42722911/44633583-05a9c200-a996-11e8-811c-7ea487bb5c4b.JPG)

**Comment by umurb** [comment]
Sorry for the delayed response.

Were you able to resolve this issue already? If not, can you please confirm if you have created your first wallet using v0.1.0b of Galleon?
