### ISSUE TITLE
I can't create a new wallet

### ISSUE THREAD

**Issue by DreamXzxy** [Cryptonomic/Deployments#9]
Hi, When I finished the password entry, but the "Create Wallet" button is gray and can't click.
![image](https://user-images.githubusercontent.com/17998878/45527225-17e88480-b80d-11e8-811a-9a391bb04043.png)

**Comment by nilskp** [comment]
You need to click the "Create Wallet File" first.

**Comment by umurb** [comment]
@nilskp is right. Closing
